name: Deploy React app to S3

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and deploy to S3
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for building the React app)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: Make deploy script executable
        run: chmod +x ./deploy.py

      - name: Run deploy script
        env:
          BUCKET: ${{ env.BUCKET }}
          AWS_REGION: ${{ env.AWS_REGION }}
          DISTRIBUTION_ID: ${{ env.DISTRIBUTION_ID }}
        run: |
          ./deploy.py --bucket "$BUCKET" --path . --region "$AWS_REGION" --distribution-id "$DISTRIBUTION_ID"
